### ISSUE TITLE
Support java.time.LocalDate

### ISSUE THREAD

**Issue by hank-whu** [json-iterator/java#122]
com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: no constructor for: class java.time.LocalDate
	at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:31)
	at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:26)
	at com.jsoniter.Codegen.gen(Codegen.java:54)
	at com.jsoniter.Codegen.getDecoder(Codegen.java:24)
	at com.jsoniter.JsonIterator.read(JsonIterator.java:369)
	at com.jsoniter.JsonIterator.read(JsonIterator.java:359)
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:425)
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:395)
	at benchmark.json.JsoniterBenchmark.deserializeUser(JsoniterBenchmark.java:84)
	at benchmark.json.generated.JsoniterBenchmark_deserializeUser_jmhTest.deserializeUser_Throughput(JsoniterBenchmark_deserializeUser_jmhTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: no constructor for: class java.time.LocalDate
	at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:31)
	at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:26)
	at com.jsoniter.Codegen.gen(Codegen.java:54)
	at com.jsoniter.Codegen.getDecoder(Codegen.java:24)
	at com.jsoniter.ReflectionObjectDecoder.addBinding(ReflectionObjectDecoder.java:88)
	at com.jsoniter.ReflectionObjectDecoder.init(ReflectionObjectDecoder.java:49)
	at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:29)
	... 21 more
Caused by: com.jsoniter.spi.JsonException: no constructor for: class java.time.LocalDate
	at com.jsoniter.ReflectionObjectDecoder.init(ReflectionObjectDecoder.java:43)
	at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:29)
	... 27 more

**Comment by gls123** [comment]
It would have been more helpful to provide an example when closing the issue - 
JsoniterSpi.registerTypeDecoder(LocalDate.class, new Decoder() {
            @Override
            public Object decode(JsonIterator iter) throws IOException {
                try {
                    return LocalDate.parse(iter.readString());
                } catch (ParseException e) {
                    throw new JsonException(e);
                }
            }
