### ISSUE TITLE
Tripple JsonException while serializing data with JsonStream

### ISSUE THREAD

**Issue by TnTGamesTV** [json-iterator/java#125]
Hey guys,
I got some exceptions while serializing my instance with JsonStream. I'm not sure what this exception is about because it is too generous. First of all here is the stack trace:

**com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: java.lang.reflect.InvocationTargetException
at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:33)
at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:328)
at com.jsoniter.output.JsonStream.serialize(JsonStream.java:351)
at com.jsoniter.output.JsonStream.serialize(JsonStream.java:370)
at com.github.tntgamestv.corganizer.timetable.TimetableProvider.saveTimetable(TimetableProvider.java:88)
at com.github.tntgamestv.corganizer.activities.timetable.edit.TimetableEditActivity$1$1.onClick(TimetableEditActivity.java:233)
[...]**

Here is the source code for TimetableProvider#saveTimetable (where the exception is thrown):

String resultA = JsonStream.serialize(timetableWeekA);
String resultB = JsonStream.serialize(timetableWeekB);

//Set data locally
StaticSettingsManager.setTimetableA(resultA);
StaticSettingsManager.setTimetableB(resultB);

//Set data in backend
CloudManager.pushTimetableData(timetableWeekA, timetableWeekB);

'timetableWeekA' and 'timetableWeekB' are both instances of the class 'TimetableBlueprint'. The blueprint is edited and should be saved as a string (aka being serialized). 

Here are the three classes that need to be serialized (which will make sense after you read the source code):

TimetableBlueprint: https://pastebin.com/unCiDJrY
Day: https://pastebin.com/wgfKdQVt
Subject: https://pastebin.com/UX3QzLyb

The only thing I know about JsonException is that it has a problem with parsing the instance (e.g. expects String and finds Integer but I'm not sure where in my classes this can happen).

I hope someone will find an error so this great library can parse my classes.

~TnTGamesTV

**Comment by taowen** [comment]
`com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:33)` I can not find the source code for this exception https://github.com/json-iterator/java/blob/master/src/main/java/com/jsoniter/output/ReflectionObjectEncoder.java

Are you using the latest version?

**Comment by TnTGamesTV** [comment]
Forgot to add my version - my bad.

I just updated from 0.9.8 to 0.9.16 and nothing changed. Same error and stack trace.
You can find the exception in `com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:39)`.
JsonException just wraps the thrown exception which is two other JsonExceptions with one `java.lang.reflect.InvocationTargetException` (which basically is another wrapper as the docs say: "InvocationTargetException is a checked exception that wraps an exception thrown by an invoked method or constructor. " - [Docs](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/InvocationTargetException.html)).

Still, no clue why serialize throws these exceptions!

**Comment by taowen** [comment]
can you provide full stacktrace? 

```
        try {
            enocde_(obj, stream);
        } catch (Exception e) {
            throw new JsonException(e);
        }
```

we need to know which line throw the exception originally. the line `throw new JsonException(e);` is a wrapper

**Comment by TnTGamesTV** [comment]
The stack trace is obviously cut, but the removed part is only an onclick listener and basic view methods for initializing an activity (using jsoniter in an android app). I'll post the full stack trace soon - currently not able to.

**Comment by TnTGamesTV** [comment]
So this is the complete stack trace copied directly from the console. I'd like to point out that for some reason the last line has something chopped away and I'm not sure why. 

But here is the stack trace:
**com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: java.lang.reflect.InvocationTargetException**
                                                                                      at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:39)
                                                                                      at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:367)
                                                                                      at com.jsoniter.output.JsonStream.serialize(JsonStream.java:476)
                                                                                      at com.jsoniter.output.JsonStream.serialize(JsonStream.java:456)
                                                                                      at com.github.tntgamestv.corganizer.timetable.TimetableProvider.saveTimetable(TimetableProvider.java:88)
                                                                                      at com.github.tntgamestv.corganizer.activities.timetable.edit.TimetableEditActivity$1$1.onClick(TimetableEditActivity.java:233)
                                                                                      at com.gc.materialdesign.widgets.Dialog$2.onClick(Dialog.java:88)
                                                                                      at com.gc.materialdesign.views.ButtonFlat.onDraw(ButtonFlat.java:83)
                                                                                      at android.view.View.draw(View.java:15242)
                                                                                      at android.view.View.getDisplayList(View.java:14136)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
                                                                                      at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
                                                                                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2747)
                                                                                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2613)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2184)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1248)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6501)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:573)
                                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
                                                                                      at android.os.Handler.handleCallback(Handler.java:733)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5476)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                                   **Caused by: com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: java.lang.reflect.InvocationTargetException**
                                                                                      at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:39)
                                                                                      at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:348)
                                                                                      at com.jsoniter.output.CodegenImplNative$1$18.encode(CodegenImplNative.java:229)
                                                                                      at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:357)
                                                                                      at com.jsoniter.output.ReflectionListEncoder.encode(ReflectionListEncoder.java:36)
                                                                                      at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:348)
                                                                                  	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(Refle

**Comment by taowen** [comment]
```java
public static class TimetableBlueprint {

        public enum Type{
            WEEK_A(0, "a"), WEEK_B(1, "b");

            private int id;
            private String name;

            Type(int id, String name){
                this.id = id;
                this.name = name;
            }

            public int getID(){
                return this.id;
            }

            public String getName(){
                return this.name;
            }
        }

        @JsonIgnore
        private TimetableBlueprint.Type type;

        private List<Day> days;

        public TimetableBlueprint(TimetableBlueprint.Type type) {
            this.type = type;
            this.days = new ArrayList<Day>();
        }

    /*Some methods that have nothing to do with the represented data*/
    }

    public static class Day {

        private List<Subject> subjects;
        private int dayIndex;
        private int week;
        private int year;

        @JsonIgnore
        private boolean absolute = false;

        public Day(){
            this.subjects = new ArrayList<Subject>();
        }

        public Day(int dayIndex, int week, int year){
            this();
            this.dayIndex = dayIndex;
            this.week = week;
            this.year = year;

            this.absolute = true;
        }

    /*Getter, setter and other methods*/
    }

    public static class Subject {

        private String name;
        private String room;
        @JsonIgnore
        private Teacher teacher;

        @JsonIgnore
        private int lesson;

        @JsonIgnore
        private Homework homework = null;

        private String teacherID;

        public Subject(int lesson, String name, String room, Teacher teacher){
            this.lesson = lesson;
            this.name = name;
            this.room = room;
            this.teacher = teacher;
        }

    /*Getter, setter and methods*/
    }

    public static class Teacher {
    }

    public static class Homework {
    }

    public void testSerialize() {
        TimetableBlueprint obj = new TimetableBlueprint(TimetableBlueprint.Type.WEEK_A);
        Day day = new Day();
        day.subjects.add(new Subject(1, "", "", new Teacher()));
        obj.days.add(day);
        System.out.println(JsonStream.serialize(obj));
    }
```

I can not reproduce the problem with above sample.

**Comment by taowen** [comment]
I made the JsonException not so deep in 0.9.18. You may want to try again, and report an exact location where the exception thrown.

**Comment by TnTGamesTV** [comment]
Okay. I'll try to find the location, but the current problem is, that androids console cannot finish logging the stack trace (that's why it's cut) so I'll try to catch the exception and then print to console so my app won't crash.

I'll post the result soon.

**Comment by TnTGamesTV** [comment]
So. This is the stack trace produced by `JsonStream.serialize(obj)`. It is cut again, but not somewhere important (in my opinion).

**com.jsoniter.spi.JsonException: java.lang.reflect.InvocationTargetException**
                                                                                      at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:41)
                                                                                      at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:348)
                                                                                      at com.jsoniter.output.CodegenImplNative$1$18.encode(CodegenImplNative.java:230)
                                                                                      at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:357)
                                                                                      at com.jsoniter.output.ReflectionListEncoder.encode(ReflectionListEncoder.java:36)
                                                                                      at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:348)
                                                                                      at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
                                                                                      at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:78)
                                                                                      at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
                                                                                      at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:348)
                                                                                      at com.jsoniter.output.CodegenImplNative$1$18.encode(CodegenImplNative.java:230)
                                                                                      at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:357)
                                                                                      at com.jsoniter.output.ReflectionListEncoder.encode(ReflectionListEncoder.java:36)
                                                                                      at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:348)
                                                                                      at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
                                                                                      at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:78)
                                                                                      at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
                                                                                      at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:367)
                                                                                      at com.jsoniter.output.JsonStream.serialize(JsonStream.java:476)
                                                                                      at com.jsoniter.output.JsonStream.serialize(JsonStream.java:456)
                                                                                      at com.github.tntgamestv.corganizer.timetable.TimetableProvider.saveTimetable(TimetableProvider.java:88)
                                                                                      at com.github.tntgamestv.corganizer.activities.timetable.edit.TimetableEditActivity$1$1.onClick(TimetableEditActivity.java:233)
                                                                                      at com.gc.materialdesign.widgets.Dialog$2.onClick(Dialog.java:88)
                                                                                      at com.gc.materialdesign.views.ButtonFlat.onDraw(ButtonFlat.java:83)
                                                                                      at android.view.View.draw(View.java:15242)
                                                                                      at android.view.View.getDisplayList(View.java:14136)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
                                                                                      at android.view.View.getDisplayList(View.java:14073)
                                                                                      at android.view.View.getDisplayList(View.java:14178)
                                                                                      at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
                                                                                      at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
                                                                                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2747)
                                                                                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2613)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2184)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1248)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6501)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:573)
                                                                                  	at android.view.Choreographer$FrameDisplayEv

**Comment by taowen** [comment]
Try mark the @JsonIgnore on getters instead of fields for Subject class

**Comment by taowen** [comment]
Or try to write a sample code which you can send to me to reproduce the
problem.

**Comment by TnTGamesTV** [comment]
So. I just added @JsonIgnore to getters in all three classes and **it works** now.
It seems like @JsonIgnore is ignored if it is only set on the class attributes (due to the private flag?). But other than that, I want to thank you (@taowen) for helping out and this library is just great.
