### ISSUE TITLE
Jsoniter fails serializing string that can be serialized with Gson.

### ISSUE THREAD

**Issue by kadaan** [json-iterator/java#126]
Jsoniter fails serializing string that can be serialized with Gson.

```
com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: Broken surrogate pair: first char 0xd83d, second 0xd83d; illegal combination
        at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:39)
        at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:367)
        at com.jsoniter.output.JsonStream.serialize(JsonStream.java:476)
        at com.jsoniter.output.JsonStream.serialize(JsonStream.java:449)
```

**Comment by taowen** [comment]
can you give me full sample code?

**Comment by anjo-swe** [comment]
@taowen here's an example:

```
import com.google.gson.Gson;
import com.jsoniter.extra.GsonCompatibilityMode;
import com.jsoniter.output.JsonStream;

public class Issue126 {

    public static void main(String... args) {

        GsonCompatibilityMode gsonConfig =
                new GsonCompatibilityMode.Builder()
                        .disableHtmlEscaping()
                        .build();

        String input = "{\"test\":\"lorem-\uD83D\uDC44\uD83D\uDC40\"}";
        TestObject testObject = new Gson().fromJson(input, TestObject.class);

        System.out.println("Gson: " + new Gson().toJson(testObject));
        System.out.println("jsoniter: " + JsonStream.serialize(gsonConfig, testObject));
    }

    private static class TestObject {
        private String test;
    }
}
```

**Comment by taowen** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/jsoniter/jsoniter/0.9.19-SNAPSHOT/jsoniter-0.9.19-20171123.034106-1.jar

**Comment by anjo-swe** [comment]
@taowen thanks a lot for the quick turnaround. Do you know when 0.9.19 will be released?
