### ISSUE TITLE
no constructor for: class com.jsoniter.spi.Config when using MaybeEmptyArrayDecoder.class

### ISSUE THREAD

**Issue by garciagars** [json-iterator/java#132]
Currently using version 0.9.18 together with retrofit for Android

When trying to deser a json whose value is sometimes    `"image":[]` 
and sometimes `"image":{....}`

Jsoniter returns an error `no constructor for: class com.jsoniter.spi.Config`

```java    
    public class Country {
      @JsonProperty(value = "category")
      private String Category;
      @JsonProperty(value = "created_at")
      private String CreatedAt;
      @JsonProperty(value = "id")
      private String Id;
      @JsonProperty(value = "image", decoder = MaybeEmptyArrayDecoder.class)
      private PhotoMedia Image;
      @JsonProperty(value = "slug")
      private String Slug;
      @JsonProperty(value = "type")
      private String Type;
      @JsonProperty(value = "updated_at")
      private String UpdatedAt;
    }
```
```java    
    public class PhotoMedia {
      @JsonProperty(value = "large")
      private String Large;
      @JsonProperty(value = "medium")
      private String Medium;
      @JsonProperty(value = "original")
      private String Original;
      @JsonProperty(value = "small")
      private String Small;
    }
```

**Comment by taowen** [comment]
can you provide full stacktrace

**Comment by garciagars** [comment]
Here's the stack trace

```
com.jsoniter.spi.JsonException: no constructor for: class com.jsoniter.spi.Config
at com.jsoniter.ReflectionObjectDecoder.init(ReflectionObjectDecoder.java:45)
at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:29)
at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:26)
at com.jsoniter.Codegen.gen(Codegen.java:55)
at com.jsoniter.Codegen.getDecoder(Codegen.java:25)
at com.jsoniter.ReflectionObjectDecoder.addBinding(ReflectionObjectDecoder.java:90)
at com.jsoniter.ReflectionObjectDecoder.init(ReflectionObjectDecoder.java:48)
at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:29)
at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:26)
at com.jsoniter.Codegen.gen(Codegen.java:55)
at com.jsoniter.Codegen.getDecoder(Codegen.java:25)
at com.jsoniter.JsonIterator.read(JsonIterator.java:326)
at com.jsoniter.fuzzy.MaybeEmptyArrayDecoder.decode(MaybeEmptyArrayDecoder.java:21)
at com.jsoniter.ReflectionObjectDecoder.decodeBinding(ReflectionObjectDecoder.java:373)
at com.jsoniter.ReflectionObjectDecoder.decodeBinding(ReflectionObjectDecoder.java:381)
at com.jsoniter.ReflectionObjectDecoder.access$700(ReflectionObjectDecoder.java:10)
at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode_(ReflectionObjectDecoder.java:164)
at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode(ReflectionObjectDecoder.java:119)
at com.jsoniter.ReflectionCollectionDecoder.decode_(ReflectionCollectionDecoder.java:47)
at com.jsoniter.ReflectionCollectionDecoder.decode(ReflectionCollectionDecoder.java:28)
at com.jsoniter.JsonIterator.read(JsonIterator.java:369)
at com.garciagars.broadsword.core.api.converter.JsoniterResponseBodyConverter.convert(JsoniterResponseBodyConverter.java:29)
at com.garciagars.broadsword.core.api.converter.JsoniterResponseBodyConverter.convert(JsoniterResponseBodyConverter.java:18)
at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
at io.reactivex.Observable.subscribe(Observable.java:10910)
at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
at io.reactivex.Observable.subscribe(Observable.java:10910)
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
```
