### ISSUE TITLE
IndexOutOfBoundsException when accessing null any array

### ISSUE THREAD

**Issue by anti43** [json-iterator/java#153]
Should any return an empty array or is it desired to get an exception for this case?

```
Any x = JsonIterator.deserialize("{\"test\":null}")
x.get('test').iterator().next()
```
error:

```
java.lang.IndexOutOfBoundsException: null
	at com.jsoniter.any.ArrayLazyAny.fillCacheUntil(ArrayLazyAny.java:163)
	at com.jsoniter.any.ArrayLazyAny.access$000(ArrayLazyAny.java:13)
	at com.jsoniter.any.ArrayLazyAny$LazyIterator.<init>(ArrayLazyAny.java:197)
	at com.jsoniter.any.ArrayLazyAny.iterator(ArrayLazyAny.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:911)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:902)
	at org.codehaus.groovy.runtime.InvokerHelper.asIterator(InvokerHelper.java:571)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3123)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3095)
	at org.codehaus.groovy.runtime.dgm$65.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
```

**Comment by taowen** [comment]
I can not reproduce this exception, what I get is `java.util.NoSuchElementException`

```java
    public void test_null() {
        Any x = JsonIterator.deserialize("{\"test\":null}");
        x.get("test").iterator().next();
    }
```
this exception is expected. null is considered as empty array, call `next()` on empty array should throw exception.
