### ISSUE TITLE
com.jsoniter.spi.JsonException: anonymous class not supported

### ISSUE THREAD

**Issue by gunnlaugursig** [json-iterator/java#172]
Thanks for great library.

I'm trying to use JsonStream.serialize for the following object but it fails with the error "**com.jsoniter.spi.JsonException: anonymous class not supported: class javax.naming.ldap.LdapName$1**"

Is there something I'm missing or am I making some mistake?

My class looks like this.
   
     import java.util.HashMap;
     import java.util.List;
     import java.util.Map;

     import javax.naming.Name;

     import org.springframework.ldap.odm.annotations.Attribute;
     import org.springframework.ldap.odm.annotations.Entry;
     import org.springframework.ldap.odm.annotations.Id;

     import com.jsoniter.annotation.JsonProperty;

     @Entry(objectClasses = { "HSS-EsmUser" }, base = "nodeName=jambala")
     public final class User {
	
	     @Id
         private Name dn;
	
	     @Attribute(name = "groupId")
	     private String groupId;
	
	     @Attribute(name = "objectClass")
	     private List<String> objectClass;
	
	     @Attribute(name = "ownerId")
	     private String ownerId;
	
	     @Attribute(name = "permissions")
	     private String permissions;
	
	     @Attribute(name = "shareTree")
	     private String shareTree;
	
	     @Attribute(name = "HSS-EsmAaaAddress")
	     @JsonProperty(required = false)
	     private String aaaAddress;

	     @Attribute(name = "HSS-EsmAaaRegistrationState")
	     @JsonProperty(required = false)
	     private String aaaRegistrationState;

	     @Attribute(name = "HSS-EsmAccessRestrictions")
	     @JsonProperty(required = false)
	     private String accessRestrictions;

	     @Attribute(name = "HSS-EsmAutomaticProvisioned")
	     private String automaticProvisioned;

	     @Attribute(name = "HSS-EsmImeiSv")
	     @JsonProperty(required = false)
	     private String imeiSv;

	     @Attribute(name = "HSS-EsmImsi")
	     private String imsi;

	     @Attribute(name = "HSS-EsmIndividualSubscribedChargingChars")
	     @JsonProperty(required = false)
	     private String individualSubscribedChargingChars;

	     @Attribute(name = "HSS-EsmLocationState")
	     @JsonProperty(required = false)
	     private String locationState;

	     @Attribute(name = "HSS-EsmLocationUserStateInfoRetrievalSupp")
	     private String locationUserStateInfoRetrievalSupp;

	     @Attribute(name = "HSS-EsmMmeAddress")
	     @JsonProperty(required = false)
	     private String mmeAddress;

	     @Attribute(name = "HSS-EsmMsisdn")
	     @JsonProperty(required = false)
	     private String msisdn;

	     @Attribute(name = "HSS-EsmOdb")
	     @JsonProperty(required = false)
	     private String odb;

	     @Attribute(name = "HSS-EsmRoamingAllowed")
	     @JsonProperty(required = false)
	     private String roamingAllowed;

	     @Attribute(name = "HSS-EsmRoamingRestriction")
	     @JsonProperty(required = false)
	     private String roamingRestriction;

	     @Attribute(name = "HSS-EsmUeSrVccCap")
	     @JsonProperty(required = false)
	     private String ueSrVccCap;

	     @Attribute(name = "HSS-EsmUserProfileId")
	     private String userProfileId;

	     @Attribute(name = "HSS-EsmIndividualApnOiReplacement")
	     @JsonProperty(required = false)
	     private String individualApnOiReplacement;

	     @Attribute(name = "HSS-EsmIndividualDefaultContextId")
	     @JsonProperty(required = false)
	     private String individualDefaultContextId;

	     @Attribute(name = "HSS-EsmIndividualContextIdList")
	     @JsonProperty(required = false)
	     private List<String> individualContextIdList;

	     @Attribute(name = "HSS-EsmIndividualMappingContextIdList")
	     @JsonProperty(required = false)
	     private List<String> individualMappingContextIdList;

	     @Attribute(name = "HSS-EsmIndividualAmbrMaxUl")
	     @JsonProperty(required = false)
	     private String individualAmbrMaxUl;

	     @Attribute(name = "HSS-EsmIndividualAmbrMaxDl")
	     @JsonProperty(required = false)
	     private String individualAmbrMaxDl;

	     @Attribute(name = "HSS-EsmIndividualRatFreqSelPriorId")
	     @JsonProperty(required = false)
	     private String individualRatFreqSelPriorId;

	     @Attribute(name = "HSS-EsmUserIpV4Address")
	     @JsonProperty(required = false)
	     private List<String> userIpV4Address;

	     @Attribute(name = "HSS-EsmUserIpV6Address")
	     @JsonProperty(required = false)
	     private List<String> userIpV6Address;

	     @Attribute(name = "HSS-EsmTenantId")
	     @JsonProperty(required = false)
	     private String tenantId;

	     @Attribute(name = "HSS-EsmDynPdnGwInfo")
	     @JsonProperty(required = false)
	     private List<String> dynPdnGwInfo;

	     @Attribute(name = "HSS-EsmStnSr")
	     @JsonProperty(required = false)
	     private String stnSr;

	     @Attribute(name = "HSS-EsmLastUpdateLocationDate")
	     @JsonProperty(required = false)
	     private String lastUpdateLocationDate;

	     @Override
	     public String toString() {
		     return "User [dn=" + dn + ", groupId=" + groupId + ", objectClass=" + objectClass + ", ownerId=" + ownerId
				+ ", permissions=" + permissions + ", shareTree=" + shareTree + ", aaaAddress=" + aaaAddress
				+ ", aaaRegistrationState=" + aaaRegistrationState + ", accessRestrictions=" + accessRestrictions
				+ ", automaticProvisioned=" + automaticProvisioned + ", imeiSv=" + imeiSv + ", imsi=" + imsi
				+ ", individualSubscribedChargingChars=" + individualSubscribedChargingChars + ", locationState="
				+ locationState + ", locationUserStateInfoRetrievalSupp=" + locationUserStateInfoRetrievalSupp
				+ ", mmeAddress=" + mmeAddress + ", msisdn=" + msisdn + ", odb=" + odb + ", roamingAllowed="
				+ roamingAllowed + ", roamingRestriction=" + roamingRestriction + ", ueSrVccCap=" + ueSrVccCap
				+ ", userProfileId=" + userProfileId + ", individualApnOiReplacement=" + individualApnOiReplacement
				+ ", individualDefaultContextId=" + individualDefaultContextId + ", individualContextIdList="
				+ individualContextIdList + ", individualMappingContextIdList=" + individualMappingContextIdList
				+ ", individualAmbrMaxUl=" + individualAmbrMaxUl + ", individualAmbrMaxDl=" + individualAmbrMaxDl
				+ ", individualRatFreqSelPriorId=" + individualRatFreqSelPriorId + ", userIpV4Address="
				+ userIpV4Address + ", userIpV6Address=" + userIpV6Address + ", tenantId=" + tenantId
				+ ", dynPdnGwInfo=" + dynPdnGwInfo + ", stnSr=" + stnSr + ", lastUpdateLocationDate="
				+ lastUpdateLocationDate + "]";
	    }

	     public Map<String, Object> clazzAttributesAsMap() {
		     Map<String, Object> map = new HashMap<>();
		     map.put("dn", dn);
		     map.put("groupId", groupId);
		     map.put("objectClass", objectClass);
		     map.put("ownerId", ownerId);
		     map.put("permissions", permissions);
		     map.put("shareTree", shareTree);
		     map.put("HSS-EsmAaaAddress", aaaAddress);
		     map.put("HSS-EsmAaaRegistrationState", aaaRegistrationState);
		     map.put("HSS-EsmAccessRestrictions", accessRestrictions);
		     map.put("HSS-EsmAutomaticProvisioned", automaticProvisioned);
		     map.put("HSS-EsmImeiSv", imeiSv);
		     map.put("HSS-EsmImsi", imsi);
		     map.put("HSS-EsmIndividualSubscribedChargingChars",     individualSubscribedChargingChars);
		     map.put("HSS-EsmLocationState", locationState);
		     map.put("HSS-EsmLocationUserStateInfoRetrievalSupp", locationUserStateInfoRetrievalSupp);
		     map.put("HSS-EsmMmeAddress", mmeAddress);
		     map.put("HSS-EsmMsisdn", msisdn);
		     map.put("HSS-EsmOdb", odb);
		     map.put("HSS-EsmRoamingAllowed", roamingAllowed);
		     map.put("HSS-EsmRoamingRestriction", roamingRestriction);
		     map.put("HSSEsmUeSrVccCap-", ueSrVccCap);
		     map.put("HSS-EsmUserProfileId", userProfileId);
		     map.put("HSS-EsmIndividualApnOiReplacement", individualApnOiReplacement);
		     map.put("HSS-EsmIndividualDefaultContextId", individualDefaultContextId);
		     map.put("HSS-EsmIndividualContextIdList", individualContextIdList);
		     map.put("HSS-EsmIndividualMappingContextIdList", individualMappingContextIdList);
		     map.put("HSS-EsmIndividualAmbrMaxUl", individualAmbrMaxUl);
		     map.put("HSS-EsmIndividualAmbrMaxDl", individualAmbrMaxDl);
		     map.put("HSS-EsmIndividualRatFreqSelPriorId", individualRatFreqSelPriorId);
		     map.put("HSS-EsmUserIpV4Address", userIpV4Address);
		     map.put("HSS-EsmUserIpV6Address", userIpV6Address);
		     map.put("HSS-EsmTenantId", tenantId);
		     map.put("HSS-EsmDynPdnGwInfo", dynPdnGwInfo);
		     map.put("HSS-EsmStnSr", stnSr);
		     map.put("HSS-EsmLastUpdateLocationDate", lastUpdateLocationDate);
		     return map;
	     }
     }

Here is how I try to serialize the object

    Optional<User> oUser = userRepository.findByMsisdn("5550101");
    User user = oUser.get();
    String u = JsonStream.serialize(user.clazzAttributesAsMap());

Stacktrace

> 2018-03-16 09:37:57.328  INFO 18390 --- [           main] is.siminn.hssldap.HssLdapApplication     : Starting HssLdapApplication on bender with PID 18390 (/home/gunnl/Documents/workspace-sts-3.7.2.RELEASE/hss-ldap/target/classes started by gunnl in /home/gunnl/Documents/workspace-sts-3.7.2.RELEASE/hss-ldap)
2018-03-16 09:37:57.330  INFO 18390 --- [           main] is.siminn.hssldap.HssLdapApplication     : No active profile set, falling back to default profiles: default
2018-03-16 09:37:57.382  INFO 18390 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@3c87521: startup date [Fri Mar 16 09:37:57 GMT 2018]; root of context hierarchy
2018-03-16 09:37:57.847  INFO 18390 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2018-03-16 09:37:58.083  INFO 18390 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-03-16 09:37:58.092  INFO 18390 --- [           main] is.siminn.hssldap.HssLdapApplication     : Started HssLdapApplication in 1.077 seconds (JVM running for 1.508)
2018-03-16 09:37:58.098  INFO 18390 --- [           main] i.s.h.repository.UserRepositoryImpl      : Find User by HSS-EsmMsisdn=5550101
2018-03-16 09:37:58.100  INFO 18390 --- [           main] i.s.h.repository.UserRepositoryImpl      : LDAP filter is (&(objectClass=HSS-EsmUser)(HSS-EsmMsisdn=5550101))
User [dn=HSS-EsmImsi=123456789012345,HSS-EsmSubscriptionId=123456789012345,HSS-EsmSubscriptionContainerName=HSS-EsmSubscriptionContainer,applicationName=HSS_ESM, groupId=0, objectClass=[HSS-EsmUser], ownerId=0, permissions=9, shareTree=nodeName=jambala, aaaAddress=, aaaRegistrationState=not_registered, accessRestrictions=36, automaticProvisioned=FALSE, imeiSv=3548430876103616, imsi=123456789012345, individualSubscribedChargingChars=8, locationState=LOCATED, locationUserStateInfoRetrievalSupp=TRUE, mmeAddress=mmec08.mmegi8000.mme.epc.mnc001.mcc274.3gppnetwork.org, msisdn=5550101, odb=NONE, roamingAllowed=TRUE, roamingRestriction=TRUE, ueSrVccCap=UE-SRVCC-NOT-SUPPORTED, userProfileId=HSS-EsmDefaultAutomaticProfile, individualApnOiReplacement=null, individualDefaultContextId=null, individualContextIdList=[], individualMappingContextIdList=[], individualAmbrMaxUl=null, individualAmbrMaxDl=null, individualRatFreqSelPriorId=null, userIpV4Address=[], userIpV6Address=[], tenantId=null, dynPdnGwInfo=[], stnSr=null, lastUpdateLocationDate=null]
2018-03-16 09:38:01.270  INFO 18390 --- [           main] ConditionEvaluationReportLoggingListener : 
> 
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-03-16 09:38:01.275 ERROR 18390 --- [           main] o.s.boot.SpringApplication               : Application run failed
> 
> java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:793) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at is.siminn.hssldap.HssLdapApplication.main(HssLdapApplication.java:14) [classes/:na]
Caused by: com.jsoniter.spi.JsonException: anonymous class not supported: class javax.naming.ldap.LdapName$1
	at com.jsoniter.spi.TypeLiteral.generateCacheKey(TypeLiteral.java:96) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.spi.TypeLiteral.generateDecoderCacheKey(TypeLiteral.java:84) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.spi.TypeLiteral.createNew(TypeLiteral.java:180) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.spi.TypeLiteral.create(TypeLiteral.java:170) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.spi.Config.getEncoderCacheKey(Config.java:65) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:347) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:78) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:348) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.CodegenImplNative$1$18.encode(CodegenImplNative.java:230) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:357) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.ReflectionMapEncoder.writeEntry(ReflectionMapEncoder.java:66) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.ReflectionMapEncoder.encode(ReflectionMapEncoder.java:49) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:367) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.JsonStream.serialize(JsonStream.java:476) ~[jsoniter-0.9.19.jar:na]
	at com.jsoniter.output.JsonStream.serialize(JsonStream.java:456) ~[jsoniter-0.9.19.jar:na]
	at is.siminn.hssldap.Runner.run(Runner.java:40) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:790) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	... 5 common frames omitted
> 
> 2018-03-16 09:38:01.276  INFO 18390 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@3c87521: startup date [Fri Mar 16 09:37:57 GMT 2018]; root of context hierarchy
2018-03-16 09:38:01.277  INFO 18390 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown

**Comment by gunnlaugursig** [comment]
Worked after I converted **javax.naming.Name** to string. It was not enough to change the signature of clazzAttributesAsMap() function and Map declaration to <Object, Object>
