### ISSUE TITLE
[BUG Report] Exception in thread "main" com.jsoniter.spi.JsonException: name conflict found

### ISSUE THREAD

**Issue by guanpengcn** [json-iterator/java#190]
public class result {
    private int f1;
    public void setF1(int n) { f1 = n;}
    public int getF1() { return f1;}

    @JsonCreator
    public result(@JsonProperty("f1") int n) {
        f1 = n;
    }
}
----------------------------------------------
public class t2 {
    public result r;
}
----------------------------------------------
public class test {
    public static void main(String[] args) {
        String json = "{\"r\":{\"f1\":99}}";
        t2 _t2new = JsonIterator.deserialize(json, t2.class);
    }
}

Exception in thread "main" com.jsoniter.spi.JsonException: name conflict found in class jsoniter.result: f1
	at com.jsoniter.ReflectionObjectDecoder.addBinding(ReflectionObjectDecoder.java:96)
	at com.jsoniter.ReflectionObjectDecoder.init(ReflectionObjectDecoder.java:51)
	at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:29)
	at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:26)
	at com.jsoniter.Codegen.gen(Codegen.java:55)
	at com.jsoniter.Codegen.getDecoder(Codegen.java:25)
	at com.jsoniter.ReflectionObjectDecoder.addBinding(ReflectionObjectDecoder.java:90)
	at com.jsoniter.ReflectionObjectDecoder.init(ReflectionObjectDecoder.java:48)
	at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:29)
	at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:26)
	at com.jsoniter.Codegen.gen(Codegen.java:55)
	at com.jsoniter.Codegen.getDecoder(Codegen.java:25)
	at com.jsoniter.JsonIterator.read(JsonIterator.java:385)
	at com.jsoniter.JsonIterator.read(JsonIterator.java:375)
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:441)
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:411)
	at jsoniter.test.main(test.java:2)

**Comment by taowen** [comment]
use `@JsonIgnore` on the properties
