### ISSUE TITLE
readIntSlowPath: value is too large for int

### ISSUE THREAD

**Issue by feeliperodrigoo** [json-iterator/java#192]
Im trying to parse a byte stream of a json file, but im getting the following error:

`com.jsoniter.spi.JsonException: readIntSlowPath: value is too large for int, head: 105, peek: ":24364962, buf: {"id":1006981218359861249,"positive":0,"negative":0,"score":"positive","lang":"en","arrivalTime":24364962061412,"departureTime":24364962061802,"metricsResult":"/Users/feliperodrigodesouza/scripts/metrics/","transferTime":0.0}
	at com.jsoniter.JsonIterator.reportError(JsonIterator.java:136)
	at com.jsoniter.IterImplForStreaming.readIntSlowPath(IterImplForStreaming.java:526)
	at com.jsoniter.IterImpl.readInt(IterImpl.java:385)
	at com.jsoniter.IterImplNumber.readInt(IterImplNumber.java:83)
	at com.jsoniter.JsonIterator.readInt(JsonIterator.java:181)
	at com.jsoniter.CodegenImplNative$2$11.decode(CodegenImplNative.java:103)
	at com.jsoniter.ReflectionObjectDecoder.decodeBinding(ReflectionObjectDecoder.java:376)
	at com.jsoniter.ReflectionObjectDecoder.decodeBinding(ReflectionObjectDecoder.java:384)
	at com.jsoniter.ReflectionObjectDecoder.access$700(ReflectionObjectDecoder.java:10)
	at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode_(ReflectionObjectDecoder.java:164)
	at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode(ReflectionObjectDecoder.java:119)
	at com.jsoniter.JsonIterator.read(JsonIterator.java:369)
	at com.jsoniter.JsonIterator.read(JsonIterator.java:359)
	at App.lambda$addParser$4c4462ea$1(App.java:303)
	at org.apache.edgent.oplet.functional.Map.accept(Map.java:45)
	at org.apache.edgent.runtime.etiao.SettableForwarder.accept(SettableForwarder.java:54)
	at org.apache.edgent.oplet.core.Source.submit(Source.java:47)
	at org.apache.edgent.oplet.functional.SupplierPeriodicSource.fetchTuples(SupplierPeriodicSource.java:52)
	at org.apache.edgent.oplet.core.PeriodicSource.run(PeriodicSource.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at org.apache.edgent.runtime.etiao.TrackingScheduledExecutor$TrackedFuture.run(TrackingScheduledExecutor.java:226)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.edgent.runtime.etiao.ThreadFactoryTracker$2.run(ThreadFactoryTracker.java:87)
	at java.lang.Thread.run(Thread.java:748)`

The reading code is the following: 

```java
    private static final TStream<Object> addParser(TStream<byte[]> msgs, TStream<Object> object){
        return msgs.map(t -> {
            try {
                return JsonIterator
                        .parse(t)
                        .read(Object.class);

            } catch (Exception e) {
                e.printStackTrace();
                return null;
            }

        })
    }
```

And im using the following code to write the json file:

```java
File file = new File("file.json");
OutputStream outputStream = new FileOutputStream(file);
BufferedWriter bufferedWriter = new BufferedWriter(new OutputStreamWriter(outputStream, "UTF-8"));
gson.toJson(tuple, Object.class, bufferedWriter);
bufferedWriter.close();
```

**Comment by taowen** [comment]
you can use double if number overflows int
