### ISSUE TITLE
Serialize error object

### ISSUE THREAD

**Issue by darlandc1998** [json-iterator/java#248]
``java
JsonStream.serialize(object)
``

Error exception
``java
Caused by: com.jsoniter.spi.JsonException: can not encode map key type: class java.util.jar.Attributes$Name
	at com.jsoniter.output.MapKeyEncoders.createDefaultEncoder(MapKeyEncoders.java:39)
	at com.jsoniter.output.MapKeyEncoders.registerOrGetExisting(MapKeyEncoders.java:17)
	at com.jsoniter.output.MapKeyEncoders$DynamicKeyEncoder.encode(MapKeyEncoders.java:74)
	at com.jsoniter.output.JsonStream.writeObjectField(JsonStream.java:340)
	at com.jsoniter.output.ReflectionMapEncoder.writeEntry(ReflectionMapEncoder.java:57)
	at com.jsoniter.output.ReflectionMapEncoder.encode(ReflectionMapEncoder.java:42)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:362)
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:74)
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:362)
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:78)
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:362)
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:78)
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:362)
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:78)
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:362)
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:74)
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:362)
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:78)
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:362)
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:74)
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:362)
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:74)
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:362)
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:74)
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:362)
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:74)
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:362)
	at com.jsoniter.output.ReflectionObjectEncoder.writeEncodeTo(ReflectionObjectEncoder.java:121)
	at com.jsoniter.output.ReflectionObjectEncoder.enocde_(ReflectionObjectEncoder.java:74)
	at com.jsoniter.output.ReflectionObjectEncoder.encode(ReflectionObjectEncoder.java:37)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:381)
	at com.jsoniter.output.JsonStream.serialize(JsonStream.java:490)
	at com.jsoniter.output.JsonStream.serialize(JsonStream.java:470)
	at br.com.twcom.gerente.rest.app.AppRest.getDados(AppRest.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:79)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:89)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:102)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:237)
	... 112 more
``

**Comment by svobol13** [comment]
@darlandc1998 can you please provide more details on what type of object are you trying to serialise?
