### ISSUE TITLE
Streaming api can't read escaped json string values

### ISSUE THREAD

**Issue by ekuleshov** [json-iterator/java#31]
The following test is failing. Jackson can read such escaped strings, as per json RFC.
```

	@Test
	public void test() throws Exception {
		JsonIterator.setMode(DecodingMode.REFLECTION_MODE);
		
		String s = "{\"cc\":\"[\\\"LL\\\",\\\"MM\\\\\\/LW\\\",\\\"JY\\\",\\\"S\\\",\\\"C\\\",\\\"IN\\\",\\\"ME \\\\\\/ LE\\\"]\"}";
		
		JsonIterator iter = JsonIterator.parse(s);
		for(String f = iter.readObject(); f != null; f = iter.readObject()) {
			String val = iter.readString();
			System.err.println(val);
		}
	}

```

Actual json is this:
{"cc":"[\"LL\",\"MM\\\/LW\",\"JY\",\"S\",\"C\",\"IN\",\"ME \\\/ LE\"]"}

Here is exception I'm getting:
com.jsoniter.spi.JsonException: readString: incomplete string, head: 10, peek: {"cc":"[, buf: {"cc":"[\"LL\",\"MM\\\/LW\",\"JY\",\"S\",\"C\",\"IN\",\"ME \\\/ LE\"]"}
	at com.jsoniter.JsonIterator.reportError(JsonIterator.java:131)
	at com.jsoniter.IterImpl.readStringSlowPath(IterImpl.java:289)
	at com.jsoniter.IterImplString.readString(IterImplString.java:98)
	at com.jsoniter.JsonIterator.readString(JsonIterator.java:196)
	at ps.TestJsoniter2.test(TestJsoniter2.java:22)

**Comment by taowen** [comment]
wow, thank you, such a big bug :(

Just fixed

**Comment by ekuleshov** [comment]
Thank you. How does affect performance of the stream API? I've tried to run forked java-json-benchmark but it wasn't update for the latest jsoniter and crashing with some exceptions.

**Comment by taowen** [comment]
this bug will not affect the performance, as the benchmarking only tested the fast path. java-json-benchmark project is out of date, I will update the code when I have time.

**Comment by Mahdihp** [comment]
03-06 17:51:09.211 30483-30483/com.mahdi.ketabcell E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.mahdi.ketabcell, PID: 30483
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mahdi.ketabcell/com.mahdi.ketabcell.activity.piccell.ShowPiccellActivity}: com.jsoniter.spi.JsonException: readString: incomplete string, head: 9, peek: {"body":", buf: {"body":"یب سمینبتشسیمن بشمسنیتب منش ستیمبشسینبتا سشیبسشنتیا بنتسیاب نتسیا بنتسیابنسشتیاب نشستی ابنتشسیابنستیابنشسیانبسشایب نسشای بنشسای نبساینبتش سینباشسنیباسشنیبا شسنیبا سنیتبا سشنیت نسیت بت سیتب اسینتبسی باسیبنسیا بنسیاب سیاب سیناب سینتبا سیتنبا سیتنبا سینت باسیبتنسی نتسی بنت سی بتس بس سنیت سین سیسینباسنیب","commentCount":0,"doILike":false,"doISuggest":false,"likeCount":0,"rowId":"58bcf9ef620b1d05f8533103","specialLabel":0,"submitDate":"2017-03-06T05:55:59.460Z","suggestCount":0,"title":"تس می باشد","type":1,"url":["images/cell/544989037.jpg"],"username":"mahdihp"}
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2219)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by taowen** [comment]
@Mahdihp can you give me a txt file with the json string?

**Comment by Mahdihp** [comment]
{"body":"یبل تیبلتیبمسش یبمک سشیمب سشیکمب تشسکمیبنمسیتبمسشتیب منشستمتبیملتیبملتیبمتلیمبلت یبلتیبل ینبنن اسی باسیش نباسشینباشسینبشسنتیب شسنیاب نشسیابنسشتیابنتسشیابنسشیابنسیشابنسشیاب نسشیاب سشیب سشیبن ت سینبسیبنسیشاب نسیاب سیاب نسیتبا سینا سیا بسیاب نستیشاب نستیبسی","commentCount":0,"doILike":false,"doISuggest":false,"likeCount":1,"rowId":"58bf6ed1c8015f0bd4422c70","specialLabel":0,"submitDate":"2017-03-08T02:39:13.568Z","suggestCount":0,"title":"تست می باشد.","type":1,"url":["images/cell/490661220.jpg"],"username":"mahdihp"}

**Comment by taowen** [comment]
```java
    public static class TestObject {
        public String body;
        public int commentCount;
    }

    public void test_utf8() {
        String input = "{\"body\":\"یبل تیبلتیبمسش یبمک سشیمب سشیکمب تشسکمیبنمسیتبمسشتیب منشستمتبیملتیبملتیبمتلیمبلت یبلتیبل ینبنن اسی باسیش نباسشینباشسینبشسنتیب شسنیاب نشسیابنسشتیابنتسشیابنسشیابنسیشابنسشیاب نسشیاب سشیب سشیبن ت سینبسیبنسیشاب نسیاب سیاب نسیتبا سینا سیا بسیاب نستیشاب نستیبسی\",\"commentCount\":0,\"doILike\":false,\"doISuggest\":false,\"likeCount\":1,\"rowId\":\"58bf6ed1c8015f0bd4422c70\",\"specialLabel\":0,\"submitDate\":\"2017-03-08T02:39:13.568Z\",\"suggestCount\":0,\"title\":\"تست می باشد.\",\"type\":1,\"url\":[\"images/cell/490661220.jpg\"],\"username\":\"mahdihp\"}";
        TestObject obj = JsonIterator.deserialize(input, TestObject.class);
        assertEquals(0, obj.commentCount);
    }
```
can not reproduce. please make sure the input is utf8, other encoding is not supported.

**Comment by tomcashman** [comment]
I have been able to reproduce this on latest version. The following test fails:

```java
final String json = "{\"str\":\"{\\\"escapedKey\\\":\\\"escapedValues\\\"}\"}";
final Any any = JsonIterator.deserialize(json);
Assert.assertEquals("{\\\"escapedKey\\\":\\\"escapedValues\\\"}", any.get("str").toString());
```
