### ISSUE TITLE
java.lang.UnsupportedClassVersionError: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by tokazio** [json-iterator/java#51]
Using your tutorial, i've tried to do static configuration but getting this exception at compile time.

The maven config:

```
<dependency>
 <groupId>com.jsoniter</groupId>
 <artifactId>jsoniter</artifactId>
 <version>0.9.10</version>
</dependency>
<dependency>
 <groupId>org.javassist</groupId>
 <artifactId>javassist</artifactId>
 <version>3.22.0-CR1</version>
</dependency>
...
<plugin>
 <groupId>org.codehaus.mojo</groupId>
 <artifactId>exec-maven-plugin</artifactId>
 <version>1.6.0</version>
  <executions>
   <execution>
    <id>static-codegen</id>
     <phase>compile</phase>
      <goals>
       <goal>exec</goal>
       </goals>
       <configuration>
        <executable>java</executable>
        <workingDirectory>${project.build.sourceDirectory}</workingDirectory>
        <arguments>
         <argument>-classpath</argument>
         <classpath/>
         <argument>com.jsoniter.StaticCodeGenerator</argument>
         <argument>net.esyo.utils.JsonUtils</argument>
        </arguments>
       </configuration>
      </execution>
     </executions>
</plugin>

```
The JsonUtils file:

```
static {
        new JsonUtils().setup();
        JsonIterator.setMode(DecodingMode.STATIC_MODE);
        JsonStream.setMode(EncodingMode.STATIC_MODE);
}

@Override
public void setup() {
}

@Override
public TypeLiteral[] whatToCodegen() {
        return new TypeLiteral[]{
            TypeLiteral.create(NetServiceConfig.class)
};
```

**Comment by taowen** [comment]
can you give me the full stacktrace of the error message?

**Comment by tokazio** [comment]
Trying the code on another platform, it seems to work (asking for decoder).
Can confirm this and give you the full stack next thuesday.

Now i'm getting:
`com.jsoniter.spi.JsonException: static gen should provide the decoder we need, but failed to create the decoder
	at com.jsoniter.Codegen.gen(Codegen.java:80)
	at com.jsoniter.Codegen.getDecoder(Codegen.java:35)
	at com.jsoniter.JsonIterator.read(JsonIterator.java:336)
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:373)
	at net.esyo.utils.JsonUtils.loadFromFile(JsonUtils.java:61)
	at net.esyo.registry.server.RegistryServer.loadConfig(RegistryServer.java:328)
	at net.esyo.registry.server.RegistryServer.main(RegistryServer.java:44)
Caused by: java.lang.ClassNotFoundException: decoder.net.esyo.registry.server.NetRegistryConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.jsoniter.Codegen.gen(Codegen.java:75)
	... 6 more`

I haven't wrote a decoder but, why is it searching decoder.net.esyo.registry.server.NetRegistryConfig? note the 'decoder' as the base package instead of 'net.esyo'.

**Comment by taowen** [comment]
static decoder works this way. it will create the the decoder source code in the package "decoder.xxx" prefixing your class name. you do not need to write the decoder, the decoder should be generated by `com.jsoniter.StaticCodeGenerator`

then in the runtime, it will search for "decoder.xxx". if in static mode, not found such class will be a fatal error, because it expects the class should be generated ahead of time. if in dynamic mode, it will trigger class generation in the runtime (using javaasist).

**Comment by tokazio** [comment]
Ok it's working on my osx installation. Just one error with a json bean file, see [this issue](https://github.com/json-iterator/java/issues/52) please.
Keep this one open, i will give you the windows stack about the UnsupportedClassVersionError.
On this windows installation i've java 7 and java 8 installed. Netbeans sources is configured with java 8 but maybe i've skip a thing...

**Comment by tokazio** [comment]
Ok, i think it's an os/ide configuration mistake with multiple jdk installation.
You can close this one.

**Comment by tokazio** [comment]
Multiple java installations misconfiguration.

**Comment by tokazio** [comment]
Using netbeans with maven. 
JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_102

Have:
jdk1.7.0_25
jdk1.7.0_79
jdk1.8.0.91
jdk1.8.0_102
jdk-9
Installed in C:\Program Files\Java

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/esyo/utils/JsonUtils : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.jsoniter.StaticCodeGenerator.main(StaticCodeGenerator.java:17)
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
```

**Comment by tokazio** [comment]
ok found this: http://stackoverflow.com/questions/4681090/how-do-i-find-where-jdk-is-installed-on-my-windows-machine

Netbeans maven process was using system32/java.exe instead of the JAVA_HOME one...
