### ISSUE TITLE
Stackoverflow

### ISSUE THREAD

**Issue by tokazio** [json-iterator/java#52]
Giving this json bean class
```
public class NetServiceConfig {

    @JsonIgnore
    private static final Logger LOGGER = LoggerFactory.getLogger(NetServiceConfig.class);

    private int port;
    private String registryAddress;
    private int registryPort;
    private String databaseConfigurationFilename;
    private String token;

    public NetServiceConfig() {
	//for json construction
    }

    public int getPort() {
	return port;
    }

    public void setPort(final int port) {
	this.port = port;
    }

    public String getRegistryAddress() {
	return registryAddress;
    }

    public void setRegistryAddress(String registryAddress) {
	this.registryAddress = registryAddress;
    }

    public int getRegistryPort() {
	return registryPort;
    }

    public void setRegistryPort(int registryPort) {
	this.registryPort = registryPort;
    }

    public File getDatabaseConfigurationFile() {
	File file = new File(databaseConfigurationFilename);
	if (!file.exists()) {
	    LOGGER.error("Database configuration file '" + file + "' doesn't exists");
	    return null;
	}
	return file;
    }

    public void setDatabaseConfigurationFilename(String filename) {
	databaseConfigurationFilename = filename;
    }

    public String getDatabaseConfigurationFilename() {
	return databaseConfigurationFilename;
    }

    public String getToken() {
	return token;
    }

    public void setToken(String token) {
	this.token = token;
    }
```
I'm getting this
```
--- exec-maven-plugin:1.5.0:exec (static-codegen) @ NetFramework ---
Exception in thread "main" java.lang.StackOverflowError
	at java.util.Currency.getInstance(Currency.java:318)
	at java.util.Currency.getInstance(Currency.java:410)
	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:638)
	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113)
	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
	at java.util.Formatter.getZero(Formatter.java:2283)
	at java.util.Formatter.<init>(Formatter.java:1892)
	at java.util.Formatter.<init>(Formatter.java:1914)
	at java.lang.String.format(String.java:2940)
	at com.jsoniter.output.CodegenResult.bufferToWriteOp(CodegenResult.java:34)
	at com.jsoniter.output.CodegenImplObject.genField(CodegenImplObject.java:90)
	at com.jsoniter.output.CodegenImplObject.genObject(CodegenImplObject.java:35)
	at com.jsoniter.output.Codegen.genSource(Codegen.java:199)
	at com.jsoniter.output.Codegen.gen(Codegen.java:121)
	at com.jsoniter.output.Codegen.getEncoder(Codegen.java:74)
	at com.jsoniter.output.CodegenImplNative.genWriteOp(CodegenImplNative.java:289)
	at com.jsoniter.output.CodegenImplObject.genField(CodegenImplObject.java:107)
	at com.jsoniter.output.CodegenImplObject.genObject(CodegenImplObject.java:35)
	at com.jsoniter.output.Codegen.genSource(Codegen.java:199)
	at com.jsoniter.output.Codegen.gen(Codegen.java:121)
	at com.jsoniter.output.Codegen.getEncoder(Codegen.java:74)...

Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
```
For 4 others of my json beans classes, it's working but not with this one.

The config:
```
@Override
    public TypeLiteral[] whatToCodegen() {
	return new TypeLiteral[]{
	    TypeLiteral.create(Registered.class),
	    TypeLiteral.create(RegisteredList.class),
	    TypeLiteral.create(NetRegistryConfig.class),
	    TypeLiteral.create(NetDiscoverConfig.class),
	    TypeLiteral.create(NetServiceConfig.class)	    
	};
    }
```

**Comment by taowen** [comment]
public File getDatabaseConfigurationFile() 

you might need to JsonIgnore this one

**Comment by tokazio** [comment]
Ok, was thinking about this just before you answer. But not working with @JsonIgnore, same exception.
It's working when I completely remove it!

**Comment by taowen** [comment]
try JsoniterAnnotationSupport.enable();

**Comment by tokazio** [comment]
... was commented out... sorry, ok it's working! niiiice
