### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by tokazio** [json-iterator/java#53]
Giving this class:
```
public class RegisteredList {

    private final List<Registered> all = new ArrayList<>();
    
    public RegisteredList(){
        //For json construct
    }
    
    public RegisteredList(List<Registered> allRegistered) {
	this.all.addAll(allRegistered);
    }

    @JsonIgnore
    public Registered get(int index){
        return all.get(index);
    }
    
    @JsonIgnore
    public RegisteredList add(Registered registered){
        this.all.add(registered);
        return this;
    }
    
    @JsonIgnore
    public int size(){
        return this.all.size();
    }

    public List<Registered> getAll() {
	return this.all;
    }  
        
    @Override
    public String toString(){
	return this.all.toString();
    }
}
```

I successfully serialize it as:
`"all":[{"serviceName":"aad","ip":"192.168.1.36","port":13112}]}`

But when deserializing:
```
String s = "{\"all\":[{\"serviceName\":\"aad\",\"ip\":\"192.168.1.36\",\"port\":13112}]}\n";
		RegisteredList liste = JsonIterator.deserialize(s, RegisteredList.class);
```

I got:
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -10
	at java.lang.String.substring(String.java:1931)
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:377)
	at net.esyo.registry.server.RegistryServer.loadLastRegisteredFromFile(RegistryServer.java:323)
	at net.esyo.registry.server.RegistryServer.<init>(RegistryServer.java:111)
	at net.esyo.registry.server.RegistryServer.main(RegistryServer.java:66)
```

**Comment by tokazio** [comment]
Noticed the '\n' in the source string:
`"{\"all\":[{\"serviceName\":\"aad\",\"ip\":\"192.168.1.36\",\"port\":13112}]}\n"`
If i remove it, there's no more exception but the RegisteredList is empty.

**Comment by taowen** [comment]
https://github.com/json-iterator/java/commit/99223e32aba686234a45c11cb4ca5f0e5ca60ed6

this version should have fixed the problem. It takes some time to sync to maven repository.

**Comment by tokazio** [comment]
ok no exception. But the list in RegisteredList:
`List<Registered> all`

Contains Registered elements with all fields as null values.
`Registered{serviceName=null, ip=null, port=0}`

Here the Registered class:
```
public class Registered implements Serializable {

    private static final transient Logger LOGGER = LoggerFactory.getLogger(Registered.class);

    private String serviceName;
    private String ip;
    private int port;

    public Registered() {
	//for json construction
    }

    public Registered(final String serviceName, final String ip, final int port) throws RegistryException {
	if(serviceName==null || serviceName.isEmpty()){
	    throw new RegistryException("Need a service name");
	}
	if(ip==null || ip.isEmpty()){
	    throw new RegistryException("Need a service ip");
	}
	if(port<0){
	    throw new RegistryException("Need a valid service port");
	}
	this.serviceName = serviceName;
	this.ip = ip;
	this.port = port;
    }

    public static Registered fromJson(final String json) {
	return JsonUtils.fromJson(json, Registered.class);
    }

    public String getIp() {
	return ip;
    }

    public String getServiceName() {
	return serviceName;
    }

    public int getPort() {
	return port;
    }

    @Override
    public int hashCode() {
	int hash = 7;
	hash = 29 * hash + Objects.hashCode(this.serviceName);
	hash = 29 * hash + Objects.hashCode(this.ip);
	hash = 29 * hash + this.port;
	return hash;
    }

    @Override
    public boolean equals(Object obj) {
	if (obj == null) {
	    return false;
	}
	if (getClass() != obj.getClass()) {
	    return false;
	}
	final Registered other = (Registered) obj;
	return serviceName.equals(other.serviceName) && ip.equals(other.ip) && port == other.port;
    }

    public boolean isAlive() {
	try (Socket sock = new Socket(getIp(), getPort())) {
	    LOGGER.info(getServiceName() + "@" + getIp() + ":" + getPort() + " still alive");
	    return true;
	} catch (IOException ex) {
	    LOGGER.warn(getServiceName() + "@" + getIp() + ":" + getPort() + " down!");
	    return false;
	}
    }

    @Override
    public String toString() {
	return "Registered{" + "serviceName=" + serviceName + ", ip=" + ip + ", port=" + port + '}';
    }
}
```
