### ISSUE TITLE
StackOverflowError in JsoniterSpi

### ISSUE THREAD

**Issue by mroloux** [json-iterator/java#70]
I'm using jsoniter inside a web application that runs on Heroku. jsoniter serializes a list of objects thorugh JsonStream.serialize

In normal loads, everything work fine. But when the server is restarted and then receives hundreds of simultaneous requests as a load test, jsoniter throws an exception:

```
2017-06-13T14:16:07.942432+00:00 app[web.4]: java.lang.StackOverflowError: null
2017-06-13T14:16:07.942433+00:00 app[web.4]: 	at com.jsoniter.spi.JsoniterSpi.getEncoder(JsoniterSpi.java:73) ~[jsoniter-0.9.12.jar:na]
2017-06-13T14:16:07.942887+00:00 app[web.4]: 	at com.jsoniter.output.Codegen$1.encode(Codegen.java:140) ~[jsoniter-0.9.12.jar:na]
2017-06-13T14:16:07.942887+00:00 app[web.4]: 	at com.jsoniter.output.Codegen$1.encode(Codegen.java:140) ~[jsoniter-0.9.12.jar:na]
2017-06-13T14:16:07.942888+00:00 app[web.4]: 	at com.jsoniter.output.Codegen$1.encode(Codegen.java:140) ~[jsoniter-0.9.12.jar:na]
2017-06-13T14:16:07.942889+00:00 app[web.4]: 	at com.jsoniter.output.Codegen$1.encode(Codegen.java:140) ~[jsoniter-0.9.12.jar:na]
2017-06-13T14:16:07.942889+00:00 app[web.4]: 	at com.jsoniter.output.Codegen$1.encode(Codegen.java:140) ~[jsoniter-0.9.12.jar:na]
2017-06-13T14:16:07.942890+00:00 app[web.4]: 	at com.jsoniter.output.Codegen$1.encode(Codegen.java:140) ~[jsoniter-0.9.12.jar:na]
2017-06-13T14:16:07.942890+00:00 app[web.4]: 	at com.jsoniter.output.Codegen$1.encode(Codegen.java:140) ~[jsoniter-0.9.12.jar:na]
2
```

Sometimes this errors does not appear again in the next requests, but in other cases it keeps on appearing. Looks like a multi-threaded initialisation problem in the library.

I could not reproduce the issue locally. The difference is that locally I'm running HotSpot VM 1.8.0_60-b27, and on Heroku it's OpenJDK 1.8.0_121.

Any ideas? Could it be related to using OpenJDK?

**Comment by taowen** [comment]
Can you try a newer version? I added some defensive code to dignose https://oss.sonatype.org/content/repositories/snapshots/com/jsoniter/jsoniter/0.9.13-SNAPSHOT/

Before codegen, a placeholder will be put into the cache, so that recursive structure can be supported. If codegen failed, the placeholder is not pulled out, so if it ends up being used, infinite loop will happen. This might because the codegen fail in heavy load or concurrent class generation, or other unexpected thing happen.

**Comment by mroloux** [comment]
Thanks. I Tried that version, but now the list gets serialised to a JSON array of empty objects, instead of objects with properties. Everything works fine when I revert back to 0.9.12.

**Comment by taowen** [comment]
can you give me an example?

**Comment by mroloux** [comment]
Sure, something like this:

```
public static void main(String[] args) {
   System.out.println(JsonStream.serialize(new AClass()));
}

private static class AClass {
   public String foo = "bar";
}
```

**Comment by taowen** [comment]
@mroloux can you try again, I uploaded a newer version. The problem is the `private static class` which is filtered (in dynamic codegen mode, unlike reflection mode private class is not accessible). I restored previous behavior, should work now.

**Comment by mroloux** [comment]
Yes, that worked. But now I receive this error when I deploy on our server, and throw a big load at it:

```
2017-06-14T09:24:03.913829+00:00 app[web.1]: com.jsoniter.spi.JsonException: internal error: placeholder is not replaced with real encoder
2017-06-14T09:24:03.913829+00:00 app[web.1]: 	at com.jsoniter.output.Codegen$1.encode(Codegen.java:120) ~[jsoniter-0.9.13-SNAPSHOT.jar:na]
2017-06-14T09:24:03.913831+00:00 app[web.1]: 	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:335) ~[jsoniter-0.9.13-SNAPSHOT.jar:na]
2017-06-14T09:24:03.913832+00:00 app[web.1]: 	at com.jsoniter.output.CodegenImplNative$1$18.encode(CodegenImplNative.java:229) ~[jsoniter-0.9.13-SNAPSHOT.jar:na]
2017-06-14T09:24:03.913832+00:00 app[web.1]: 	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:344) ~[jsoniter-0.9.13-SNAPSHOT.jar:na]
2017-06-14T09:24:03.913833+00:00 app[web.1]: 	at com.jsoniter.output.ReflectionListEncoder.encode(ReflectionListEncoder.java:35) ~[jsoniter-0.9.13-SNAPSHOT.jar:na]
2017-06-14T09:24:03.913834+00:00 app[web.1]: 	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:354) ~[jsoniter-0.9.13-SNAPSHOT.jar:na]
2017-06-14T09:24:03.913834+00:00 app[web.1]: 	at com.jsoniter.output.JsonStream.serialize(JsonStream.java:422) ~[jsoniter-0.9.13-SNAPSHOT.jar:na]
2017-06-14T09:24:03.913835+00:00 app[web.1]: 	at com.jsoniter.output.JsonStream.serialize(JsonStream.java:464) ~[jsoniter-0.9.13-SNAPSHOT.jar:na]
2017-06-14T09:24:03.913836+00:00 app[web.1]: 	at com.jsoniter.output.JsonStream.serialize(JsonStream.java:443) ~[jsoniter-0.9.13-SNAPSHOT.jar:na]
```

**Comment by taowen** [comment]
I see, because there is a duration between the placeholder and real encoder kick in. So another thread is picked up the placeholder, which is still in middle of real codegen. 

Do you see this error repeatedly, or for a few of requests during the startup?

**Comment by taowen** [comment]
@mroloux can you try again. added 30 seconds wait

**Comment by mroloux** [comment]
Yes, that seems to work. Thanks!

**Comment by taowen** [comment]
Yeah~
