### ISSUE TITLE
Indention step not impl in dynamic mode

### ISSUE THREAD

**Issue by caoli5288** [json-iterator/java#81]
> Example
```Java
public class Main {

    public static class Foo {

        public int i1;
        public int i2 = 1;
    }

    public static void main(String[] ignore) {
        Config build = JsoniterSpi.getCurrentConfig().copyBuilder().indentionStep(2).build();
        JsoniterSpi.setDefaultConfig(build);
        JsoniterSpi.setCurrentConfig(build);
        JsonStream.setMode(EncodingMode.DYNAMIC_MODE);
        System.out.println(JsonStream.serialize(new Foo()));
        JsonStream.setMode(EncodingMode.REFLECTION_MODE);
        System.out.println(JsonStream.serialize(new Foo()));
    }
}
```

> Result
```
{"i1":0,"i2":1}
{
  "i1": 0,
  "i2": 1
}
```

**Comment by caoli5288** [comment]
这个我做完了，你代码一推，boom

**Comment by taowen** [comment]
比你想得要复杂，好多地方要改的。之前不支持是因为没有config，后来添加了config才使得多版本codegen成为可能。

**Comment by caoli5288** [comment]
其实我的疑问在于，直接调用`write*Start()`, `write*End()`, `writeMore()`这几个方法，真的会慢很多么，就拿`writeMore()`这个方法来说，内联`writeIndention()`后的形式为,
```
public final void writeMore() throws IOException {
    write(',');
    if (indention == 0) {
        return;
    }
    write('\n');
    int toWrite = indention - delta;
    ensure(toWrite);
    for (int i = 0; i < toWrite && count < buf.length; i++) {
        buf[count++] = ' ';
    }
}
```
如果本身没有开indention，那么仅仅多了一次`if (indention == 0)`，完全在可以忽略的范围内，完全没有必要为这生成两种动态代码，

**Comment by taowen** [comment]
因为 dsljson 是这么干的。我完全照搬过的。不会慢很多，一点点。主要成本是write操作内部去检查数组越界的成本。

**Comment by caoli5288** [comment]
其实你跟我说声，要if判断下，生成不同的代码来做，我改pull就好了，本身我已经把Object，Array，Map这三种的都做好了，花了不少时间trace你的代码，也就多加个if的事情，OTZ

**Comment by taowen** [comment]
sorry :(

indention还是我来加吧。omitDefault 就交给你吧。还有omitNull现在默认是true，可以加一个全局的配置。omitDefault 在JsonProperty上加一个默认值是什么的配置。

**Comment by caoli5288** [comment]
发现新bug，，，还是动态代码生成，indention部分的，
```Java
public class Main {

    public static class A {

        @JsonProperty(omitNull = false)
        public Integer i;
    }

    public static void main(String[] ignore) {
        Config build = JsoniterSpi.getCurrentConfig().copyBuilder()
                .indentionStep(2)
                .encodingMode(EncodingMode.DYNAMIC_MODE)
                .build();
        System.out.println(JsonStream.serialize(build, new A()));
    }
}
```
> Result
```
Exception in thread "main" com.jsoniter.spi.JsonException: failed to generate encoder for: class com.jsoniter.Main$A with [], exception: javassist.CannotCompileException: [source error] no such field: notFirst
public static void encode_(com.jsoniter.Main.A obj, com.jsoniter.output.JsonStream stream) throws java.io.IOException {
stream.writeObjectStart();
stream.writeIndention();
stream.writeObjectField("i");
if (obj.i == null) { stream.writeNull(); } else {
stream.writeVal((java.lang.Integer)obj.i);
}
if (notFirst) { stream.writeObjectEnd(); } else { stream.write('}'); }
}

	at com.jsoniter.output.Codegen.gen(Codegen.java:111)
	at com.jsoniter.output.Codegen.getEncoder(Codegen.java:50)
	at com.jsoniter.output.JsonStream.writeVal(JsonStream.java:368)
	at com.jsoniter.output.JsonStream.serialize(JsonStream.java:477)
	at com.jsoniter.output.JsonStream.serialize(JsonStream.java:450)
	at com.jsoniter.Main.main(Main.java:25)
Caused by: javassist.CannotCompileException: [source error] no such field: notFirst
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
	at com.jsoniter.output.DynamicCodegen.gen(DynamicCodegen.java:19)
	at com.jsoniter.output.Codegen.gen(Codegen.java:103)
	... 5 more
Caused by: compile error: no such field: notFirst
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
	at javassist.compiler.ast.Member.accept(Member.java:39)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.compileBooleanExpr(CodeGen.java:236)
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:384)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:355)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
	at javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:274)
	at javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:44)
	at javassist.compiler.Javac.compileMethod(Javac.java:169)
	at javassist.compiler.Javac.compile(Javac.java:95)
	at javassist.CtNewMethod.make(CtNewMethod.java:74)
	... 8 more
```
触发方式，同时设置`@JsonProperty(omitNull = false)`与`indentionStep()`，目测是`CodegenResult.buffer()`的锅，

我还是去睡觉吧，再不睡要死人了

**Comment by taowen** [comment]
it is done

**Comment by caoli5288** [comment]
great
