### ISSUE TITLE
can't read field value through JsonProperty 

### ISSUE THREAD

**Issue by inpot** [json-iterator/java#94]
here is the code,
```java
String test ="{\"rs\":true,\"code\":200}";
TestEntity entity = JsonIterator.deserialize(test, TestEntity.class);
 Log.i(TAG, "testJsoniter2: " + entity.toString());
```
```java
public class TestEntity {
    public String error;
    @JsonProperty(value = "rs", required = true)
    public boolean result;
    @JsonProperty(value = "code",required = true)
    public int code2;

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("code=");
        builder.append(code2);
        builder.append(" rs=");
        builder.append(result);
        return builder.toString();

    }
}
```
json-iterator can't read the custom field "last_modify", and throw an exception
> 07-31 15:45:30.271 30809-30809/com.jsoniter.test W/System.err: com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: missing required properties: [rs, code]
07-31 15:45:30.272 30809-30809/com.jsoniter.test W/System.err:     at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode(ReflectionObjectDecoder.java:119)
07-31 15:45:30.272 30809-30809/com.jsoniter.test W/System.err:     at com.jsoniter.JsonIterator.read(JsonIterator.java:369)
07-31 15:45:30.272 30809-30809/com.jsoniter.test W/System.err:     at jsoniter.JsoniterResponseBodyConverter.convert(JsoniterResponseBodyConverter.java:44)
07-31 15:45:30.272 30809-30809/com.jsoniter.test W/System.err:     at jsoniter.JsoniterResponseBodyConverter.convert(JsoniterResponseBodyConverter.java:30)
07-31 15:45:30.272 30809-30809/com.jsoniter.test W/System.err:     at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
07-31 15:45:30.272 30809-30809/com.jsoniter.test W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
07-31 15:45:30.272 30809-30809/com.jsoniter.test W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
07-31 15:45:30.273 30809-30809/com.jsoniter.test W/System.err:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
07-31 15:45:30.273 30809-30809/com.jsoniter.test W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10901)
07-31 15:45:30.273 30809-30809/com.jsoniter.test W/System.err:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
07-31 15:45:30.273 30809-30809/com.jsoniter.test W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10901)
07-31 15:45:30.273 30809-30809/com.jsoniter.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
07-31 15:45:30.273 30809-30809/com.jsoniter.test W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
07-31 15:45:30.273 30809-30809/com.jsoniter.test W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
07-31 15:45:30.273 30809-30809/com.jsoniter.test W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
07-31 15:45:30.273 30809-30809/com.jsoniter.test W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-31 15:45:30.273 30809-30809/com.jsoniter.test W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-31 15:45:30.273 30809-30809/com.jsoniter.test W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-31 15:45:30.274 30809-30809/com.jsoniter.test W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-31 15:45:30.274 30809-30809/com.jsoniter.test W/System.err:     at java.lang.Thread.run(Thread.java:761)
07-31 15:45:30.274 30809-30809/com.jsoniter.test W/System.err: Caused by: com.jsoniter.spi.JsonException: missing required properties: [rs, code]
07-31 15:45:30.274 30809-30809/com.jsoniter.test W/System.err:     at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode_(ReflectionObjectDecoder.java:165)
07-31 15:45:30.274 30809-30809/com.jsoniter.test W/System.err:     at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode(ReflectionObjectDecoder.java:117)
07-31 15:45:30.274 30809-30809/com.jsoniter.test W/System.err: 	... 19 more

This is right as I'v used?

**Comment by taowen** [comment]
which field is "last_modify"?

**Comment by taowen** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/jsoniter/jsoniter/0.9.16-SNAPSHOT/

should be fixed

**Comment by inpot** [comment]
i'v updated the java code serval times, here is the new log: 
>                                      com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: missing required properties: [rs, code]
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: missing required properties: [rs, code]
                                                       at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode(ReflectionObjectDecoder.java:119)
                                                       at com.jsoniter.JsonIterator.read(JsonIterator.java:369)
                                                       at com.jsoniter.JsonIterator.read(JsonIterator.java:359)
                                                       at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:425)
                                                       at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:395)

**Comment by inpot** [comment]
I'v build a jar after you fix this issue, there throw  another exception ：
>   Caused by: com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: failed to create binding for field: private transient java.lang.Class java.lang.Object.shadow$_klass_
                                                       at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:31)
                                                       at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:26)
                                                       at com.jsoniter.Codegen.gen(Codegen.java:54)
                                                       at com.jsoniter.Codegen.getDecoder(Codegen.java:24)
                                                       at com.jsoniter.JsonIterator.read(JsonIterator.java:369)
                                                       at com.jsoniter.JsonIterator.read(JsonIterator.java:359)
                                                       at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:425)
                                                       at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:395)
                                                       at com.jsoniter.test.MainActivity.testJsoniter2(MainActivity.java:34)
                                                       at com.jsoniter.test.MainActivity.onCreate(MainActivity.java:30)
                                                       at android.app.Activity.performCreate(Activity.java:6679)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6126) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                    Caused by: com.jsoniter.spi.JsonException: failed to create binding for field: private transient java.lang.Class java.lang.Object.shadow$_klass_
                                                       at com.jsoniter.spi.ClassDescriptor.createBindingFromField(ClassDescriptor.java:232)
                                                       at com.jsoniter.spi.ClassDescriptor.getFields(ClassDescriptor.java:212)
                                                       at com.jsoniter.spi.ClassDescriptor.getDecodingClassDescriptor(ClassDescriptor.java:37)
                                                       at com.jsoniter.ReflectionObjectDecoder.init(ReflectionObjectDecoder.java:37)
                                                       at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:29)
                                                       at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:26) 
                                                       at com.jsoniter.Codegen.gen(Codegen.java:54) 
                                                       at com.jsoniter.Codegen.getDecoder(Codegen.java:24) 
                                                       at com.jsoniter.JsonIterator.read(JsonIterator.java:369) 
                                                       at com.jsoniter.JsonIterator.read(JsonIterator.java:359) 
                                                       at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:425) 
                                                       at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:395) 
                                                       at com.jsoniter.test.MainActivity.testJsoniter2(MainActivity.java:34) 
                                                       at com.jsoniter.test.MainActivity.onCreate(MainActivity.java:30) 
                                                       at android.app.Activity.performCreate(Activity.java:6679) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6126) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                    Caused by: com.jsoniter.spi.JsonException: failed to generate cache key for: ParameterizedTypeImpl{actualTypeArguments=[?], ownerType=null, rawType=java.lang.Class}
                                                       at com.jsoniter.spi.TypeLiteral.generateCacheKey(TypeLiteral.java:114)
                                                       at com.jsoniter.spi.TypeLiteral.generateDecoderCacheKey(TypeLiteral.java:83)
                                                       at com.jsoniter.spi.TypeLiteral.createNew(TypeLiteral.java:172)
                                                       at com.jsoniter.spi.TypeLiteral.create(TypeLiteral.java:162)
                                                       at com.jsoniter.spi.Binding.<init>(Binding.java:40)
                                                       at com.jsoniter.spi.ClassDescriptor.createBindingFromField(ClassDescriptor.java:224)
                                                       at com.jsoniter.spi.ClassDescriptor.getFields(ClassDescriptor.java:212) 
                                                       at com.jsoniter.spi.ClassDescriptor.getDecodingClassDescriptor(ClassDescriptor.java:37) 
                                                       at com.jsoniter.ReflectionObjectDecoder.init(ReflectionObjectDecoder.java:37) 
                                                       at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:29) 
                                                       at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:26) 
                                                       at com.jsoniter.Codegen.gen(Codegen.java:54) 
                                                       at com.jsoniter.Codegen.getDecoder(Codegen.java:24) 
                                                       at com.jsoniter.JsonIterator.read(JsonIterator.java:369) 
                                                       at com.jsoniter.JsonIterator.read(JsonIterator.java:359) 
                                                       at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:425) 
                                                       at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:395) 
                                                       at com.jsoniter.test.MainActivity.testJsoniter2(MainActivity.java:34) 
                                                       at com.jsoniter.test.MainActivity.onCreate(MainActivity.java:30) 
                                                       at android.app.Activity.performCreate(Activity.java:6679) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6126) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                    Caused by: com.jsoniter.spi.JsonException: unsupported type: ?, of class class libcore.reflect.WildcardTypeImpl
                                                       at com.jsoniter.spi.TypeLiteral.formatTypeWithoutSpecialCharacter(TypeLiteral.java:145)
                                                       at com.jsoniter.spi.TypeLiteral.generateCacheKey(TypeLiteral.java:109)
                                                       at com.jsoniter.spi.TypeLiteral.generateDecoderCacheKey(TypeLiteral.java:83) 
                                                       at com.jsoniter.spi.TypeLiteral.createNew(TypeLiteral.java:172) 
                                                       at com.jsoniter.spi.TypeLiteral.create(TypeLiteral.java:162) 
                                                       at com.jsoniter.spi.Binding.<init>(Binding.java:40) 
                                                       at com.jsoniter.spi.ClassDescriptor.createBindingFromField(ClassDescriptor.java:224) 
                                                       at com.jsoniter.spi.ClassDescriptor.getFields(ClassDescriptor.java:212) 
                                                       at com.jsoniter.spi.ClassDescriptor.getDecodingClassDescriptor(ClassDescriptor.java:37) 
                                                       at com.jsoniter.ReflectionObjectDecoder.init(ReflectionObjectDecoder.java:37) 
                                                       at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:29) 
                                                       at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:26) 
                                                       at com.jsoniter.Codegen.gen(Codegen.java:54) 
                                                       at com.jsoniter.Codegen.getDecoder(Codegen.java:24) 
                                                       at com.jsoniter.JsonIterator.read(JsonIterator.java:369) 
                                                       at com.jsoniter.JsonIterator.read(JsonIterator.java:359) 
                                                       at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:425) 
                                                       at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:395) 
                                                       at com.jsoniter.test.MainActivity.testJsoniter2(MainActivity.java:34) 
                                                       at com.jsoniter.test.MainActivity.onCreate(MainActivity.java:30) 
                                                       at android.app.Activity.performCreate(Activity.java:6679) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6126) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by taowen** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/jsoniter/jsoniter/0.9.16-SNAPSHOT/

should be fixed now
